### PR TITLE
Removes placeholder text for new review, adds flash warning

### PR DESCRIPTION
**Pull request by NicoleCarpenter**

### CODE REVIEW

**Comment by hnlee** [comment]
Shouldn't there be an integration test and a controller test for the validation behavior? Otherwise, it looks pretty good to me.

**Comment by NicoleCarpenter** [comment]
Oops, yeah, forgot to commit them, good catch.

**Comment by NicoleCarpenter** [comment]
Oh, I did not write an integration test I guess.

**Comment by NicoleCarpenter** [comment]
fixed

**Comment by hnlee** [comment]
👍 Looks fantastic

**Pull request merged**
